print("Mam na imię Mateusz i narysuję trapez.")  # tutaj wpisz swoje imię
print("***")
print("*  *")
print("*   *")
print("*    *")
print("*     *")
print("*      *")
print("*       *")
print("*        *")
print("*         *")
print("*          *")
print("*           *")
print("*            *")
print("*             *")
print("****************")
